version: '3.9'

networks:
  service:
    name: service

volumes:
  pg-vol:
  node_modules:

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - service

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - PGDATA:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-vol:/var/lib/postgresql/data
    networks:
      - service
