version: '3.8'

networks:
  my-network:
    name: custom-network
    driver: bridge

volumes:
  pgdb:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    networks:
      - my-network
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    container_name: db
    volumes:
      - pgdb:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
