version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - custom-network

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    restart: always
    command: postgres -c logging_collector=on
    env_file:
      - .env
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - custom-network

volumes:
  postgres-data:
networks:
  custom-network:
    driver: bridge
